name = "GeometricDatasets"
uuid = "b92f1397-7bd4-4d1a-aad5-e469f2dd85cb"
authors = ["G. Vituri <56522687+vituri@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
